name: Rust

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-ci:
    name: Complete Rust CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true
      
      - name: Build with cargo
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-targets

      - name: Lint code with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps --keep-going --all-targets --all-features -Z unstable-options
      
      - name: Test code with cargo
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-targets

      - name: Check formatting with fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
